server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
      stream:
        binders:  #此处配置要绑定的RabbitMq服务信息
          defaultRabbit: #表示定义的名称，用于binding整合
            type: rabbit  #消息组件类型
            environment: #设置rabbitMq的相关的环境配置
              spring:
                rabbitmq:
                  host: 47.107.47.13
                  port: 5672
                  username: admin
                  password: admin
                  virtual-host: /ad-Vhost #vhost名称
        bindings: #服务的整合处理
          output: #这个名字是一个通道的名称
            destination: studyExchange  #表示要使用的exchange名称定义
            content-type: application/json  #设置消息类型，本次为json，文本设置为"text/plain"
            binder: defaultRabbit #设置要绑定的消息服务的具体设置

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: send-8801.com
    prefer-ip-address: true
